name: first workflow
on:
  push:
    branches: [main]
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Lint with Flake8
      run: make lint
    - name: Run test
      run: pytest --junitxml=tests/output/results.xml
    - name: Upload test results
      if: success() && github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./tests/output/
