name: first workflow
on:
  push:
    branches: [main]
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with Flake8
      run: make lint
    - name: Run test
      run: pytest --maxfail=1 --disable-warnings -q