name: self-runner test workflow
on:
  push:
    branches: [main]
jobs:
  lint:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Lint with Flake8
      run: |
        pip install flake8
        flake8 src tests
  test:
    runs-on: self-hosted
    # needs: lint
    steps:
    - name: Run test
      run: pytest --junitxml=tests/output/results.xml
    - name: Upload test results
      if: success() && github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./tests/output/
