name: self-runner test workflow
on:
  push:
    branches: [main]
jobs:
  lint:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Lint with Flake8
      run: |
        pip install flake8
        flake8 src tests
  test:
    runs-on: self-hosted
    needs: lint
    steps:
    - name: checkout code
      uses: actions/checkout@v4

